###v3.25.0
scenes.heroselectscene.seedfinder=Seedfinder
scenes.heroselectscene.seedfinder_nowin=You can use Seedfinder to _search for a custom seed_ with certain items according to your input, _scout a custom seed_ for all items, or _scout today's Daily Run_. Note that the same seed and game version always generate the same dungeon!\n\n_You must win at least one game before you are able to use the Seedfinder._

scenes.heroselectscene.seed_analysis=Seed Analysis
scenes.heroselectscene.unlock_title=Unlock Everything
scenes.heroselectscene.unlock_message=Impatient, are ya? Same tbh.\n\nThis _hidden option_ will skip the intro sequence, give you the _SKIPPED TUTORIAL_ Badge, and unlock everything that isn't initially available:\n\n**-** Access _all 12 heroes_\n**-** Enable _challenges_\n**-** Set _custom seeds_\n**-** Participate in _daily runs_\n\nYou won't need to do this again on this device unless you reset your data or re-install. Are you sure about this?
scenes.heroselectscene.unlock_yes=Yes, do it!
scenes.heroselectscene.unlock_no=Nevermind

scenes.titlescene$changesbutton.playstore=Go to Google Play Store

scenes.changesscene.github_link=Go to GitHub Page
scenes.changesscene.rpd_prefix=EPD is forked from RPD v3.40.0-FINAL. The changes in the repo releases should be correct, unless superseded by EPD changes.\n\nOriginal message from _Hoto-Mocha (Cocoa)_:
scenes.changesscene.rpd_changes=The game is still incomplete, has a short update cycle, and may have frequent changes that are the same or similar, so it's inefficient to mark them down in the game, so I don't put the changes in the game.\n\nDetails of changes can be found in the Github release by version.
scenes.changesscene.spd_prefix=EPD %1$s was rebased to SPD %2$s. The changes below should be correct, unless superseded by EPD changes.

scenes.seedfindscene.title=Seedfinder

scenes.seedfindscene.find_seed_button=Find Seed
scenes.seedfindscene.scout_seed_button=Scout Seed
scenes.seedfindscene.scout_daily_button=Scout Daily Run
scenes.seedfindscene.info_button=Seedfinder Info
scenes.seedfindscene.options_button=Seedfinder Options

scenes.seedfindscene.result_title=Search Result

scenes.seedfindscene.seedfinder_title=Find Seed
scenes.seedfindscene.seedfinder_info=Enter the items you want Seedfinder to find. Each item must be written on a new line. Search options can be changed in _Seedfinder Settings_. Check _Seedfinder Info_ for more details.
scenes.seedfindscene.seedfinder_yes=Find
scenes.seedfindscene.seedfinder_no=Clear

scenes.seedfindscene.scout_title=Scout Seed
scenes.seedfindscene.scout_info=Enter a valid custom seed and Seedfinder will list all the items. Search options can be changed in _Seedfinder Settings_. Check _Seedfinder Info_ for more details.
scenes.seedfindscene.scout_yes=Go
scenes.seedfindscene.scout_no=Clear

scenes.seedfindscene.scout_daily_title=Scout Daily Run
scenes.seedfindscene.scout_daily_body=Scout today's Daily Run? Seedfinder will list all the items. Search options can be changed in _Seedfinder Settings_. Check _Seedfinder Info_ for more details.
scenes.seedfindscene.scout_daily_yes=Yes
scenes.seedfindscene.scout_daily_no=No

scenes.seedfindscene.info_title=Seedfinder Info
scenes.seedfindscene.info_body=Seedfinder has 3 modes:\n\n**-** _Find Seed:_ Search for a custom seed with items that you input. Each item name must be on its own line, and can have an upgrade number "+N". Partial item names are allowed (e.g. "sharpshooting +1" will match "Ring of Sharpshooting +1"). All matching items will be _highlighted_.\n\n**-** _Scout Seed:_ Scout a custom seed for all items. The following are highlighted: _Scroll of Upgrade_, _Potion of Strength_, _Entrance/Exit_ rooms.\n\n**-** _Scout Daily Run_: Scout today's Daily Run.\n\nNote that the same seed and game version always generate the same dungeon!\nSearch options can be changed in _Seedfinder Settings_ and applies to all 3 modes. The rooms on each non-boss floor are also listed and can be searched with an option.

scenes.seedfindscene.searching_title=Seedfinder
scenes.seedfindscene.searching_text=Searching...
scenes.seedfindscene.searching_cancel=Cancel