###v3.25.0
scenes.heroselectscene.seedfinder=Seedfinder
scenes.heroselectscene.seed_analysis=Seed Analysis

scenes.titlescene$changesbutton.playstore=Go to Google Play Store

scenes.changesscene.github_link=Go to GitHub Page
scenes.changesscene.rpd_prefix=EPD is forked from RPD v3.40.0-FINAL. The changes in the repo releases should be correct, unless superseded by EPD changes.\n\nOriginal message from _Hoto-Mocha (Cocoa)_:
scenes.changesscene.rpd_changes=The game is still incomplete, has a short update cycle, and may have frequent changes that are the same or similar, so it's inefficient to mark them down in the game, so I don't put the changes in the game.\n\nDetails of changes can be found in the Github release by version.
scenes.changesscene.spd_prefix=EPD %1$s was rebased to SPD %2$s. The changes below should be correct, unless superseded by EPD changes.

scenes.seedfindscene.title=Seedfinder

scenes.seedfindscene.find_seed_button=Find Seed
scenes.seedfindscene.scout_seed_button=Scout Seed
scenes.seedfindscene.scout_daily_button=Scout Daily Run
scenes.seedfindscene.options_button=Seedfinder Options

scenes.seedfindscene.result_title=Search Result

scenes.seedfindscene.seedfinder_title=Find Seed
scenes.seedfindscene.seedfinder_info=Enter the items you want Seedfinder to find. Each item must be written on a new line. Search options can be changed. Consult the guide for more info.
scenes.seedfindscene.seedfinder_yes=find
scenes.seedfindscene.seedfinder_no=clear

scenes.seedfindscene.scout_title=Scout Seed
scenes.seedfindscene.scout_info=Enter a valid custom seed and Seedfinder will list all the items and quests. Search options can be changed. Consult the guide for more info.
scenes.seedfindscene.scout_yes=go
scenes.seedfindscene.scout_no=clear

scenes.seedfindscene.searching_title=Seedfinder
scenes.seedfindscene.searching_text=Searching...
scenes.seedfindscene.searching_cancel=Cancel