###v3.25.0
scenes.heroselectscene.seed_find=Seed Search
scenes.heroselectscene.seed_analysis=Seed Analysis
scenes.heroselectscene.unlock_title=Unlock Everything
scenes.heroselectscene.unlock_message=Impatient, are ya? Same tbh.\n\nThis _hidden option_ will give you the _SKIPPED TUTORIAL_ Badge, and unlock everything that isn't available on startup: access _all 12 heroes,_ enable _challenges,_ set _custom seeds,_ and participate in _daily runs._ You won't need to do this again on this device unless you reset your data or re-install. Are you sure about this?
scenes.heroselectscene.unlock_yes=Yes, do it!
scenes.heroselectscene.unlock_no=Nevermind

scenes.titlescene$changesbutton.playstore=Go to Google Play Store

scenes.changesscene.github_link=Go to GitHub Page
scenes.changesscene.rpd_prefix=EPD is forked from RPD v3.40.0-FINAL. The changes in the repo releases should be correct, unless superseded by EPD changes.\n\nOriginal message from _Hoto-Mocha (Cocoa)_:
scenes.changesscene.rpd_changes=The game is still incomplete, has a short update cycle, and may have frequent changes that are the same or similar, so it's inefficient to mark them down in the game, so I don't put the changes in the game.\n\nDetails of changes can be found in the Github release by version.
scenes.changesscene.spd_prefix=EPD %1$s was rebased to SPD %2$s. The changes below should be correct, unless superseded by EPD changes.
scenes.seedfindscene.title=Finding seed
scenes.seedfindscene.body=List the item names what you want, using a new line for each (press Enter).
scenes.seedfindscene.initial_value=31floor end
scenes.seedfindscene.find=Find

scenes.seedanalysisscene.title=The same seed from the same game version will always produce the same dungeon! _Please enter the seed you want to analyze_.

seedfindscene.up_to_floor=floor end
seedfindscene.floor=floor


