###v3.3.0
windows.wndbuild.title=Select the building to build
windows.wndbuild.rope_req=(%d rope)

###v3.12.0
windows.wndsettings$uitab.comfirm_yes=Exit the game
windows.wndsettings$uitab.comfirm_no=Exit later

windows.wndsettings$uitab.ui_settings=UI Settings
windows.wndsettings$uitab.ui_original=ARPD Design
windows.wndsettings$uitab.ui_shattered=SPD Design
windows.wndsettings$uitab.ui_blue_archive=BAPD Design
windows.wndsettings$uitab.ui_comfirm_desc=The UI design has changed, and you must exit and relaunch the game for the changes to be applied properly.\n\nAre you sure you want to exit the game now?
windows.wndsettings$uitab.ui_current=Current UI Design:

windows.wndupgrade.chance_bonus=Chance Bonus

###v3.27.0
windows.wndupgrade.arrow_damage=Arrow Damage
windows.wndupgrade.bullet_damage=Bullet Damage

###v3.29.0
windows.wndupgrade.thunder_damage=Thunder Damage

###v3.37.0
windows.wndsettings$datatab.google_play_upload=_Google Play 업로드_
windows.wndsettings$datatab.google_play_download=_Google Play 다운로드_
windows.wndsettings$datatab.google_upload_launched=Google Play Games에 데이터를 업로드했습니다.
windows.wndsettings$datatab.google_download_launched=Google Play Games에서 데이터를 다운로드했습니다. 반영이 되지 않았다면 게임을 재시작해보세요.

windows.wndchanger.title=Transform an Item
windows.wndchanger.desc=Transforming an item permanently changes it:
windows.wndchanger.tier=Tier
windows.wndchanger.ability=Ability
windows.wndchanger.damage=Damage
windows.wndchanger.dart_damage=Dart Damage
windows.wndchanger.bleeding=Bleeding
windows.wndchanger.blocking=Blocking
windows.wndchanger.weight=Weight
windows.wndchanger.unided=You don't know the properties of this item, its un-upgraded state is shown here.
windows.wndchanger.chance=Transforming this item has a %d%% chance to succeed!
windows.wndchanger.transform=Transform
windows.wndchanger.back=Back
windows.wndchanger.arrow_damage=Arrow Damage
windows.wndchanger.bullet_damage=Bullet Damage
windows.wndchanger.bullet_shots=Shots / Round
windows.wndchanger.blueprint_success=The blueprint has a %.0f%% chance to succeed.

windows.wndseedfindermenu.title=Seedfinder Settings
windows.wndseedfindermenu.floors_title=Max Depth: _%dF_
windows.wndseedfindermenu.floors_info=Maximum dungeon depth that Seedfinder should scout in all 3 modes.
windows.wndseedfindermenu.fontsize_title=Font Size: _%d_
windows.wndseedfindermenu.fontsize_info=Font size of the search result.
windows.wndseedfindermenu$wndloggingopts.title=Logging Options
windows.wndseedfindermenu$wndloggingopts.trinkets=Log Trinkets
windows.wndseedfindermenu$wndloggingopts.equipment=Log Equipment
windows.wndseedfindermenu$wndloggingopts.scrolls=Log Scrolls
windows.wndseedfindermenu$wndloggingopts.potions=Log Potions
windows.wndseedfindermenu$wndloggingopts.rings=Log Rings
windows.wndseedfindermenu$wndloggingopts.wands=Log Wands
windows.wndseedfindermenu$wndloggingopts.artifacts=Log Artifacts
windows.wndseedfindermenu$wndloggingopts.misc=Log Other Items
windows.wndseedfindermenu$wndloggingopts.use_rooms=Search Room Types
windows.wndseedfindermenu$wndloggingopts.rooms_info=Match _room types_ during a seed search.
windows.wndseedfindermenu$wndloggingopts.blacklist=Ignore Blacklist
windows.wndseedfindermenu$wndloggingopts.blacklist_info=Show blacklisted items that are normally not shown or matched in the search results: _gold, keys, dewdrops, energy crystals, quest items,_ and _guidebook pages._
windows.wndseedfindermenu$wndloggingopts.shops=Log Shop Items
windows.wndseedfindermenu$wndloggingopts.shops_info=Show and match _shop items_ in the search results.
windows.wndseedfindermenu.challenges=Challenges
windows.wndseedfindermenu.mode_all=_ALL_ Mode
windows.wndseedfindermenu.mode_any=_ANY_ Mode
windows.wndseedfindermenu.mode_info=_ANY Mode:_ Find a seed that contains any one of the input items.\n\n\
  _ALL Mode:_ Find a seed that contains all input items.

windows.wndseedfindermenu$wndsearchopts.title=Search Options
windows.wndseedfindermenu$wndsearchopts.multi=Multi-Range
windows.wndseedfindermenu$wndsearchopts.multi_info=Enable "multi-range" search. If a search item is followed by a comma and a number, Seedfinder will only search for that item in depths up to that number (e.g. _"Whip,4"_ will match a _Whip_ in 3F, but not one in 7F.)\n\n\
  If no number is given or it exceeds the _Max Depth_ option, Seedfinder will only search up to the max depth.
windows.wndseedfindermenu$wndsearchopts.exact=Match Exact Levels
windows.wndseedfindermenu$wndsearchopts.exact_info=Only match exact item levels, if an upgrade number is given (e.g. _"Sword +1"_ will match _Sword +1_, but not _Sword +2_.)
windows.wndseedfindermenu$wndsearchopts.use_rooms=Search Room Types
windows.wndseedfindermenu$wndsearchopts.rooms_info=Match _room types_ during a seed search (e.g. _"sacrifice"_ will match _Sacrifice Room_.)
